# Site settings
title: Dulaj Chathuranga | dulajchathuranga.com
description: A Blog about Computer Science and Programming by Dulaj Chathuranga
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://dulajchathuranga.com

# User settings
username: Dulaj Chathuranga
user_description: I am an Internet Entrepreneur interested in Artificial Intelligence and Machine Learining based in Colombo, Sri Lanka.
user_title: Internet Entrepreneur
email: dulaj.chathuranga@outlook.com
twitter_username: DulajChathu
github_username:  DulajChathuranga
gplus_username:  lorem_ipsum
paginate:            5
paginate_path: "blog/page/:num/"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

# The list of pages to show in the header of blog

pages_list:       {'Archive':'/blog/archive'}
