# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Site settings
title: Dulaj Chathuranga
description: Dulaj Chathuranga | A Blog about Artificial Intelligence
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://dulajchathuranga.com

# User settings
username: Dulaj Chathuranga
user_description: I am an Artificial Intelligence and Machine Learining Enthusiast based in Colombo, Sri Lanka.
user_title: Artificial Intelligence Enthusiast
email: dulaj.chathuranga@outlook.com
twitter_username: DulajChathu
github_username:  DulajChathuranga
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

# The list of pages to show in the header of blog

pages_list:       {'Archive':'/blog/archive'}
