# Site settings
title: Dulaj Chathuranga
description: Dulaj Chathuranga | Artificial Intelligence Blog
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dulaj Chathuranga
user_description: I am an Artificial Intelligence and Machine Learining Enthusiast.
user_title: Artificial Intelligence Enthusiast
email: dulaj.chathuranga@outlook.com
twitter_username: DulajChathu
github_username:  DulajChathuranga
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
